name: Documentation Build & Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/dgocs.yml'
  pull_request: # this is just for testing, remove after we validate it works
    types: [opened, reopened, synchronize]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV # once a week

      - name: Cache mkdocs-material
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: pip install mkdocs-material

      - name: Build & deploy docs
        run: mkdocs gh-deploy